version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - ./gradlew build --info
artifacts:
  files:
    - build/libs/devops-demo-app-0.0.1-SNAPSHOT.jar
  discard-paths: yes
